# Site settings
title: Geo, Data, Software and Science
email: ste.menegon@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Geospatial stuff, Open Data, Open Software, Open Science.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://menegon.github.io" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  menegon

# Build settings
markdown: kramdown
